# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[plugins]

[plugins.zsh-autosuggestions]
github = 'zsh-users/zsh-autosuggestions'

[plugins.fast-syntax-highlighting]
github = 'zdharma-continuum/fast-syntax-highlighting'
use = ['*.plugin.zsh']

[plugins.zsh-autocomplete]
github = 'marlonrichert/zsh-autocomplete'
use = ['*.plugin.zsh']

[plugins.ohmyzsh-config]
inline = '''
export ZSH=$HOME/.sheldon/repos/github.com/ohmyzsh/ohmyzsh
ZSH_CACHE_DIR=$ZSH/cache
ZSH_THEME=ys

add_fpath /opt/homebrew/share/zsh/site-functions


plugins=(
    git
    pip
    rust
    docker
    pyenv
    z
    brew
    poetry
    tmux
)
'''

[plugins.ohmyzsh]
github = 'ohmyzsh/ohmyzsh'
use = ['oh-my-zsh.sh']
