set -g mouse on
# Status bar
set -g status-bg black
set -g status-fg white
set-option -g status-justify centre
set-option -g status-left '#[fg=cyan][#{session_name}]'
set-option -g status-right '#{prefix_highlight} | %a %Y-%m-%d %H:%M'
set-option -g status-left-length 25

bind -n "C-\\" run "#{@popup-toggle} -w75% -h75% -Ed'##{pane_current_path}'"


# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'cutbypham/tmux-fzf-session-switch'
set -g @plugin 'loichyan/tmux-toggle-popup'

set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'

set -g @fzf-goto-session 'C-]'
set -g @fzf-goto-session-without-prefix 'true'
set -g @fzf-goto-preview-enabled 'true'



run '~/.tmux/plugins/tpm/tpm'
